# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbFileInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DbPath', models.CharField(max_length=200)),
                ('TablePath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DbInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DbName', models.CharField(max_length=50)),
                ('TableName', models.CharField(max_length=500)),
                ('UpTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DbUserInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HostUser', models.CharField(max_length=20)),
                ('HostPwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HostIp', models.GenericIPAddressField(unique=True)),
                ('HostDescription', models.CharField(max_length=500)),
                ('DelBit', models.BooleanField(default=False)),
                ('AddTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostMsg',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HostId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.HostInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProjeckInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ProgeckName', models.CharField(max_length=500)),
                ('DelBit', models.BooleanField(default=False)),
                ('AddTime', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hostmsg',
            name='ProjeckId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.ProjeckInfo'),
        ),
        migrations.AddField(
            model_name='dbuserinfo',
            name='HostId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.HostInfo'),
        ),
        migrations.AddField(
            model_name='dbinfo',
            name='HostId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.HostInfo'),
        ),
        migrations.AddField(
            model_name='dbfileinfo',
            name='HostId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.HostInfo'),
        ),
    ]
