# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170301_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinfo',
            name='HostId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.DbUserInfo'),
        ),
        migrations.AlterField(
            model_name='dbuserinfo',
            name='HostId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.HostInfo'),
        ),
    ]
