# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170301_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinfo',
            name='HostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DbUserInfo'),
        ),
    ]
