# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170301_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ProgectName', models.CharField(max_length=500)),
                ('ProgectDescription', models.CharField(max_length=500)),
                ('DelBit', models.BooleanField(default=False)),
                ('AddTime', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hostmsg',
            name='ProjeckId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.ProjectInfo'),
        ),
        migrations.DeleteModel(
            name='ProjeckInfo',
        ),
    ]
