# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170302_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmsg',
            name='ProjeckId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ProjectInfo'),
        ),
    ]
