# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170306_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostmsg',
            old_name='ProjeckId',
            new_name='ProjectId',
        ),
    ]
